### ISSUE TITLE
South Korea styles not working

### ISSUE THREAD

**Issue by spawnbn** [Joniff/Terratype#22]
For some reason, map styles are not applying for South Korea region, here is the [screenshot](http://prntscr.com/jr5sa7).

Steps to reproduce:
1. Install latest blank Umbraco project or starter (at this moment it is 7.10.4)
2. Add new Data Type -> Terratype
3. Configure Terratype to use Google Maps V3
4. Coordinate System: WGS-84
5. Version: Stable
6. Styling: Red Alert
7. Default Location: 37.553867,126.991524
8. Zoom out map until you see styles not being applied to the certain zoom level.

Regards,
Sasa

**Comment by Joniff** [comment]
Apparently its South Korean Law.... yeah, agreed I had no idea either.

See https://stackoverflow.com/questions/31568460/google-maps-style-does-not-apply-to-the-korea-area

**Comment by spawnbn** [comment]
Thank you Joniff.

Regards,
Sasa
