### ISSUE TITLE
Map taking excessive time to load (5s timeout?)

### ISSUE THREAD

**Issue by AlphaDelta** [Joniff/Terratype#23]
My  Google (stable) map seems to be taking an excessive amount of time to load when rendered on the front end (it loads pretty much instantly in the back-office).

This piece of code seems to be the offender

```JAVASCRIPT
refresh: function (m) {
	m._ignoreEvents++;
	root.google.maps.event.addListenerOnce(m.handle, 'idle', function () {
		if (m._idle == null) {
			return;
		}
		m._ignoreEvents--;
		if (m._ignoreEvents == 0) {
			q._checkResetCenter(m);
		}
		if (m._idle) {
			root.clearTimeout(m._idle);
		}
	});
	m._idle = root.setTimeout(function () {
		if (m._ignoreEvents != 0) {
			q._checkResetCenter(m);
			m._ignoreEvents = 0
		}
		root.clearTimeout(m._idle);
		m._idle = null;
	}, 5000);
	root.google.maps.event.trigger(m.handle, 'resize');
}
```
^[Terratype.GoogleMapsV3.Renderer.js 251-274](https://github.com/Joniff/Terratype/blob/e590e554f18b02ed360ead6c6d0bc32beb1d91f4/src/Terratype.GoogleMapsV3/App_Plugins/Terratype.GoogleMapsV3/Scripts/Terratype.GoogleMapsV3.Renderer.js#L251-L274)

The map is rendered like so: `@Html.Terratype(root.GetPropertyValue<Terratype.Models.Model>("map"))`. Changing the DomMonitorType doesn't seem to affect the issue in any way.

Setting the opacity to 1 on the `TerratypeGoogleMaps` div showed that the map was actually loaded entirely, it appears as though that the idle event never actually fires on the map unless the map is interacted with first either from user input or programmatically.

I've put the following rule in my style sheet as a work-around for now;

```CSS
.Terratype div[id^="TerratypeGoogleMaps"] {
	opacity: 1 !important;
}
```

However I'd still like to know what the purpose of the 5000ms timeout is and if I'm able to avoid hitting it somehow.

**Comment by Joniff** [comment]
Have released version 1.0.19 to rectify this issue.

You were correct that there was an issue with the highlighted code, have rewritten code to match my expectations.

Thank you for taking the time to report this. Very much appreciated.
