### ISSUE TITLE
Change Google API Key?

### ISSUE THREAD

**Issue by anthonyharvey77** [Joniff/Terratype#25]
How do you change the API key being used? Cannot find the source. 

Recent google data/quota usage changes means maps are not functioning based on original api key.

**Comment by Joniff** [comment]
Have answered over here
https://our.umbraco.com/projects/backoffice-extensions/terratype/bugs-questions/93142-change-google-api-key

**Comment by anthonyharvey77** [comment]
Thanks, will continue over there. Closing.
