### ISSUE TITLE
Getting error when using Terratype with Fluidity.

### ISSUE THREAD

**Issue by bdsoko** [Joniff/Terratype#27]
I could use some assistance getting Terratype to work correctly with Fluidity

My issue is with rendering the map client-side while looping through my entity object - where I'm getting: **Object reference not set to an instance of an object**.

Please note, Umbraco back office is working as expected.

My entity model looks like the following: 

```
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Map { get; set; }
    }
```

I've tried a couple of ideas as detailed in my code below

```
@foreach (var p in Model.Content.Locations.Cast<Location>())
{
    if (p.Map != null)
    {
        var map = JsonConvert.DeserializeObject<Terratype.Models.Model>(p.Map);
        //var map = JsonConvert.DeserializeObject<Terratype.Models.Model>(p.Map);
        @Html.Terratype(map)
    }
}
```

An example of how the data is stored in my custom table looks like:
```
{
  "zoom": 7,
  "position": {
    "id": "WGS84",
    "datum": "41.076381,-85.119466"
  }
}
```

Any ideas on what I'm doing wrong or if this is even possible with Fluidity?

**Comment by Joniff** [comment]
Sadly the json block you are trying to cast to Terratype.Models.Model contains about 3% of the stuff required to be able to render properly (Think about it, it has no idea whether you want a Google Map or Bing, let alone what API Keys to use, styling or icon - none of that stuff is present), but the most important part is that either it contains the config information or can bind to a property type so it can get the config required (See [Relevant Source Code](https://github.com/Joniff/Terratype/blob/master/src/Core/Terratype/Models/Model.cs#L230) which contains 3 different fallbacks to try and get the config)

I could give a long winded explanation of how to construct a valid config, but to be quicker is to switch your issue around. Don't try and render the map that is in Fluidity, instead render a map that really does exist somewhere in content and instead set the zoom and position values that you have in Fluidity instead.

See [This Forum Post](https://our.umbraco.com/packages/backoffice-extensions/terratype/bugs-questions/94481-change-map-style-at-runtime#comment-298836)  for an example of this approach.

**Comment by bdsoko** [comment]
Your suggestion is working well.  Thank you for the quick response.
