### ISSUE TITLE
Cannot create new model

### ISSUE THREAD

**Issue by vamone** [Joniff/Terratype#29]
Hello, 
I'm unable to create new model of "Model" by passing the json into the constructor.

It fails to DeserializeObject. Please see the json below. Exception message is: Cannot access child value on Newtonsoft.Json.Linq.JValue.

`{
	"provider": {
		"id": "Terratype.GoogleMapsV3",
		"version": "3",
		"apiKey": "",
		"forceHttps": true,
		"language": "",
		"predefineStyling": "dark",
		"showRoads": true,
		"showLandmarks": true,
		"showLabels": true,
		"styles": [{
				"elementType": "geometry",
				"stylers": [{
						"color": "#212121"
					}
				]
			}, {
				"elementType": "labels.icon",
				"stylers": [{
						"visibility": "off"
					}
				]
			}, {
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#757575"
					}
				]
			}, {
				"elementType": "labels.text.stroke",
				"stylers": [{
						"color": "#212121"
					}
				]
			}, {
				"featureType": "administrative",
				"featureType": "administrative",
				"elementType": "geometry",
				"stylers": [{
						"color": "#757575"
					}
				]
			}, {
				"featureType": "administrative.country",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#9e9e9e"
					}
				]
			}, {
				"featureType": "administrative.land_parcel",
				"stylers": [{
						"visibility": "off"
					}
				]
			}, {
				"featureType": "administrative.locality",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#bdbdbd"
					}
				]
			}, {
				"featureType": "poi",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#757575"
					}
				]
			}, {
				"featureType": "poi.park",
				"elementType": "geometry",
				"stylers": [{
						"color": "#181818"
					}
				]
			}, {
				"featureType": "poi.park",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#616161"
					}
				]
			}, {
				"featureType": "poi.park",
				"elementType": "labels.text.stroke",
				"stylers": [{
						"color": "#1b1b1b"
					}
				]
			}, {
				"featureType": "road",
				"elementType": "geometry.fill",
				"stylers": [{
						"color": "#2c2c2c"
					}
				]
			}, {
				"featureType": "road",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#8a8a8a"
					}
				]
			}, {
				"featureType": "road.arterial",
				"elementType": "geometry",
				"stylers": [{
						"color": "#373737"
					}
				]
			}, {
				"featureType": "road.highway",
				"elementType": "geometry",
				"stylers": [{
						"color": "#3c3c3c"
					}
				]
			}, {
				"featureType": "road.highway.controlled_access",
				"elementType": "geometry",
				"stylers": [{
						"color": "#4e4e4e"
					}
				]
			}, {
				"featureType": "road.local",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#616161"
					}
				]
			}, {
				"featureType": "transit",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#757575"
					}
				]
			}, {
				"featureType": "water",
				"elementType": "geometry",
				"stylers": [{
						"color": "#000000"
					}
				]
			}, {
				"featureType": "water",
				"elementType": "labels.text.fill",
				"stylers": [{
						"color": "#3d3d3d"
					}
				]
			}
		],
		"variety": {
			"basic": true,
			"satellite": false,
			"terrain": false,
			"selector": {
				"type": 1,
				"position": 0
			}
		},
		"streetView": {
			"enable": false,
			"position": 0
		},
		"fullscreen": {
			"enable": false,
			"position": 0
		},
		"scale": {
			"enable": false,
			"position": 0
		},
		"zoomControl": {
			"enable": true,
			"position": 9
		},
		"search": null
	},
	"position": {
		"id": "WGS84",
		"datum": "51.515592,-0.302147"
	},
	"icon": {
		"id": "redmarker",
		"url": "https://mt.google.com/vt/icon/name=icons/spotlight/spotlight-poi.png",
		"size": {
			"width": 22,
			"height": 40
		},
		"anchor": {
			"horizontal": "center",
			"vertical": "bottom"
		}
	},
	"zoom": 17,
	"lookup": "Ealing, London W5 2NX, UK",
	"label": null,
	"height": 400
}
`

**Comment by Joniff** [comment]
Sadly you can't, this issue arises due to a design decision that was made back at the start. Part of the information the model requires to be able to render correctly is stored in the datatype configuration (At the time your created the Terratype datatype), when it can't bind to this because it only been fed a json model for example, maybe returned from an examine index, it can't instantiate itself properly.

Work around can be to have a known Terratype map created on a high level content node, like a site node or setting node and then switch in and out the coordinates with values stored in your json blob.

**Comment by vamone** [comment]
Thank you very much for your reply. 

I've copied the logic from the Unit tests with PrivateObject.
