### ISSUE TITLE
Can you set location by entering postcode/zipcode?

### ISSUE THREAD

**Issue by Neilmiller74** [Joniff/Terratype#30]
Hi,

Just installed this for a client to replace angular google maps. The client was saying with angular google maps they can select map location using postcodes. Is it possible to do it with terratype googlemapsv3? All i can see is a lat/long field 

Thanks.

**Comment by Joniff** [comment]
The lat/long field is displayed directly after the map, but above the map you can select for there to be a search field where you can type anything that might be understood by Google as a location (places, postcodes, businesses). It also has an autocomplete feature too. This is pretty much the same search functionality you see elsewhere around the web including on maps.google.com

tl/dr Yes, you need to switch on search.
![image](https://user-images.githubusercontent.com/12765209/77108885-e57ba100-6a1a-11ea-8b2e-fe1b1798a9ae.png)

**Comment by Neilmiller74** [comment]
Aha, and it was as simple as that!

Many thanks sir :)
